//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindARoute.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindARoute.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string Change_Lang {
            get {
                return ResourceManager.GetString("Change_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue forward .
        /// </summary>
        public static string ContinueForward {
            get {
                return ResourceManager.GetString("ContinueForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a route.
        /// </summary>
        public static string FindRoute {
            get {
                return ResourceManager.GetString("FindRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ico_Logo {
            get {
                object obj = ResourceManager.GetObject("ico_Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] img_LangRep {
            get {
                object obj = ResourceManager.GetObject("img_LangRep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] img_LocateMe {
            get {
                object obj = ResourceManager.GetObject("img_LocateMe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] img_Logo {
            get {
                object obj = ResourceManager.GetObject("img_Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app uses WiFi to determine your position while using the app. The only data saved is your last inputted searches. No data is shared &amp; the app is usable without this.
        ///.
        /// </summary>
        public static string InitPopup {
            get {
                return ResourceManager.GetString("InitPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to junction.
        /// </summary>
        public static string Junction {
            get {
                return ResourceManager.GetString("Junction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate me.
        /// </summary>
        public static string LocateMe {
            get {
                return ResourceManager.GetString("LocateMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to: .
        /// </summary>
        public static string NavingTo {
            get {
                return ResourceManager.GetString("NavingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found for input.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-locate me.
        /// </summary>
        public static string ReLocateMe {
            get {
                return ResourceManager.GetString("ReLocateMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name.
        /// </summary>
        public static string RoomName {
            get {
                return ResourceManager.GetString("RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , then .
        /// </summary>
        public static string Then {
            get {
                return ResourceManager.GetString("Then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to use WiFi positioning, please turn on &quot;Location&quot; and allow the &quot;Location&quot; permission in app settings. This can be changed later in in-app settings..
        /// </summary>
        public static string TogglePopup {
            get {
                return ResourceManager.GetString("TogglePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t use WiFi Positioning.
        /// </summary>
        public static string TogglePopup_No {
            get {
                return ResourceManager.GetString("TogglePopup_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use WiFi Positioning.
        /// </summary>
        public static string TogglePopup_Yes {
            get {
                return ResourceManager.GetString("TogglePopup_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn left.
        /// </summary>
        public static string TurnLeft {
            get {
                return ResourceManager.GetString("TurnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn right.
        /// </summary>
        public static string TurnRight {
            get {
                return ResourceManager.GetString("TurnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search....
        /// </summary>
        public static string TypeHere {
            get {
                return ResourceManager.GetString("TypeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until .
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi Positioning.
        /// </summary>
        public static string WiFiPos {
            get {
                return ResourceManager.GetString("WiFiPos", resourceCulture);
            }
        }
    }
}
